services:
  stakeholders-db:
    image: postgres:16
    container_name: stakeholders-db
    environment:
      POSTGRES_DB: stakeholders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - stakeholders_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-network

  stakeholders-service:
    build:
      context: ./stakeholders-service
      dockerfile: Dockerfile
    container_name: stakeholders-service
    restart: on-failure
    depends_on:
      - stakeholders-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stakeholders-db:5432/stakeholders_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      JWT_SECRET: my-super-secret-jwt-key-2026-test
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    networks:
      - soa-network
  
  blog-mongo:
    image: mongo:7
    container_name: blog-mongo
    ports:
      - "27017:27017"
    volumes:
      - blog_mongo_data:/data/db
    networks:
      - soa-network

  blog-db:
    image: postgres:16
    container_name: blog-db
    environment:
      POSTGRES_DB: touristapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - blog_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-network

  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    container_name: blog-service
    restart: on-failure
    depends_on:
      - blog-db
      - blog-mongo
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      DATABASE_HOST: blog-db
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: touristapp
      DATABASE_SCHEMA_NAME: blog
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_POOLING: "true"
      MONGO_CONNECTION_STRING: mongodb://blog-mongo:27017
      MONGO_DATABASE: blog
      Jwt__Secret: my-super-secret-jwt-key-2026-test
      Jwt__Expiration: 86400000
    ports:
      - "8081:80"
    networks:
      - soa-network

    # follower treba da se dokerizuje zbog gateway-a

  follower-neo4j:
    image: neo4j:5
    container_name: follower-neo4j
    environment:
      NEO4J_AUTH: neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - follower_neo4j_data:/data
    networks:
      - soa-network

  follower-service:
    build:
      context: ./follower-service
      dockerfile: Dockerfile
    container_name: follower-service
    restart: on-failure
    depends_on:
      - follower-neo4j
    environment:
      PORT: 8082
      NEO4J_URI: bolt://follower-neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password123
      JWT_SECRET: my-super-secret-jwt-key-2026-test
    ports:
      - "8084:8082"
    networks:
      - soa-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: soa-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - stakeholders-db
      - blog-db
    networks:
      - soa-network

  tours-db:
    image: postgres:16
    container_name: tours-db
    environment:
      POSTGRES_DB: touristapp_tours
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - tours_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-network

  tour-service:
    build:
      context: ./tour-service
      dockerfile: Dockerfile
    container_name: tour-service
    restart: on-failure
    depends_on:
      - tours-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_HOST=tours-db
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=touristapp_tours
      - DATABASE_SCHEMA_NAME=tours
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_POOLING=true
      - Jwt__Secret=my-super-secret-jwt-key-2026-test
      - Jwt__Expiration=86400000
    ports:
      - "8083:80"
    networks:
      - soa-network

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway
    restart: on-failure
    depends_on:
      - blog-service
      - stakeholders-service
      - tour-service
      - follower-service
    ports:
      - "8082:80"
    networks:
      - soa-network

volumes:
  stakeholders_postgres_data:
  blog_postgres_data:
  follower_neo4j_data:
  blog_mongo_data:
  tours_postgres_data:

networks:
  soa-network:
    driver: bridge
