basePath: /follower
definitions:
  model.FollowRequest:
    properties:
      followingId:
        type: integer
    type: object
host: localhost:8082
info:
  contact: {}
  description: API for following users and recommending profiles using Neo4j graph
    database.
  title: Follower Service API
  version: "1.0"
paths:
  /api/followers/can-comment:
    get:
      description: User can comment only if they follow the blog author
      parameters:
      - description: Blog author user ID
        in: query
        name: authorId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Check if authenticated user can comment on author's blog
      tags:
      - followers
  /api/followers/follow:
    post:
      consumes:
      - application/json
      description: Creates FOLLOWS relationship between authenticated user and selected
        user
      parameters:
      - description: Follow request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.FollowRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Follow user
      tags:
      - followers
  /api/followers/recommendations:
    get:
      description: Returns users followed by the people that authenticated user already
        follows
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                format: int64
                type: integer
              type: array
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get profile recommendations
      tags:
      - followers
  /api/followers/unfollow:
    delete:
      consumes:
      - application/json
      description: Deletes FOLLOWS relationship between authenticated user and selected
        user
      parameters:
      - description: Unfollow request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.FollowRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Unfollow user
      tags:
      - followers
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
