[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  timeout = "5s"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  metric_version = 2